### ISSUE TITLE
Does theme or preset param need to be part of user's site object?

### ISSUE THREAD

**Issue by fivetwelve** [toitoi-co/toitoi-admin#21]
During onboard flow, user is asked to choose a theme (preset). Should this be saved to the user object? Our proof of concept, at the moment, shows the available themes for the user and their site is deployed upon selection. However, they should be able to deploy their site after onboarding without having to select the theme again.

**Comment by fivetwelve** [comment]
@pudly may want to be aware of this since it affects UX.

**Comment by joepie91** [comment]
The preset is currently not stored in the User object, no. Rather, it's kept on the `-generate` server entirely - once a 'switch preset' call is made to it, it will download and unpack the new preset, and all subsequent build processes will use this new preset.

`-admin` has no idea what a user's preset is right now at all, but we should probably change this so that we can visually highlight the currently-selected preset. This would only be for bookkeeping, though - `-generate` would still be the 'canonical' source for what preset a user (or rather, their site) uses, and the CMS would have to report the change to both services independently.

**Comment by joepie91** [comment]
Fixed in 695e69ba5450495783d627b9e3d1fa83886f4578.
